# Generated by Django 4.2.5 on 2023-10-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('fightid', models.AutoField(db_column='FightId', primary_key=True, serialize=False)),
                ('fighter_f', models.IntegerField(db_column='FighterF')),
                ('fighter_s', models.IntegerField(db_column='FighterS')),
            ],
            options={
                'db_table': 'fights',
            },
        ),
    ]
