# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  django:
    # Сборка образа для сервиса django из текущей директории
    build: .
    image: podolnayaaa/my_pokemonsss_django
    # Задание имени контейнера для сервиса django
    container_name: django-test
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: python manage.py test quickstart
    volumes:
      - .:/usr/src/app
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - 8000:8000
    # Зависимость от другого сервиса
    depends_on:
      - db
      - redis
  db:
    # Использование готового образа postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  redis:
    image: redis:7.0.9-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --port "${REDIS_PORT}"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data


volumes:
  postgres_data:
  redis-data: